[package]
name = "minimal-axolotlsay"
description = "💬 a CLI for learning to distribute CLIs in rust"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/axodotdev/minimal-axolotlsay"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
unicode-width = "0.1.10"

[dev-dependencies]
assert_cmd = "2.0.8"
